bart.geojson:
	# github.com/mapbox/togeojson
	npm install -g togeojson
	# http://www.bart.gov/schedules/developers/geo.aspx
	curl -O "http://api.bart.gov/kml/bart.kml"
	togeojson bart.kml > bart.geojson